version: "3.8"

services:
  database:
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: bookstore_db
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_USER: admin
      MYSQL_PASSWORD: talha123
    networks:
      - bookstore-net
    volumes: 
    - bookstore:/var/lib/mysql
    configs:
    - source: table
      target: /docker-entrypoint-initdb.d
  app-server:
    build: ./api-server
    image: talha/bookstore-api:v1
    restart: always
    depends_on:
      - database
    ports:
      - "500:80"
    networks:
      - bookstore-net
  metric-server:
    build: ./metric-server
    image: talha/metric-bookstore-api:v1
    restart: always
    depends_on:
      - database
    ports:
      - "501:88"
    networks:
      - bookstore-net
  prometheus: 
    image: prom/prometheus:latest
    container_name: prometheus
    ports: 
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana: 
    image: grafana/grafana
    container_name: grafana
    ports: 
    - 3000:3000
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
    - prometheus
    
networks:
  bookstore-net:

volumes: 
  bookstore:
    
configs: 
  table: 
    file: ./config/init.sql